# Setup
title:               martinezhero.org
tagline:             Joe DiMaggio Hometown Hero Project
url:                 https://martinezhero.org
baseurl:             ""

# Assets
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Josef Kelly
  email:             josefkelly@pm.me

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/martinez-hero/martinez-hero.github.io

collections:
  - board_members
  - honorary_members
  - president
